what is function transformer in machine learning ?

The Function Transformer is a tool in scikit-learn, a popular
Python library for machine learning, that allows you to apply a
specified function to the input data. The Function Transformer
can be useful for performing custom transformations of input
data in a machine learning pipeline.

In [6]:
from sklearn.preprocessing import FunctionTransformer
import numpy as np

# create a dataset
X = np.array([[1, 2], [3, 4]])

# define the transformation function
log_transform = FunctionTransformer(np.log1p)

# apply the transformation to the dataset
X_transformed = log_transform.transform(X)

# view the transformed data
print(X_transformed)

[[0.69314718 1.09861229]
 [1.38629436 1.60943791]]


In [8]:
# create a dataset
X = np.array([[1, 2], [3, 4]])

# define a custom feature engineering function
def squ(X):
    return np.hstack((X, X**2))

# create a FunctionTransformer to apply the custom function
custom_transformer = FunctionTransformer(squ)

# apply the transformer to the input data
X_transformed = custom_transformer.transform(X)

# view the transformed data
print(X_transformed)

[[ 1  2  1  4]
 [ 3  4  9 16]]


In [15]:
X = np.array([[x for x in range (21,51)]])

def even(X):
    return X[X % 2 == 0]

custom_transformer = FunctionTransformer(even)

X_transformed = custom_transformer.transform(X)

print(X_transformed)

[22 24 26 28 30 32 34 36 38 40 42 44 46 48 50]


In [17]:
# create a dataset
X = np.array([[1, 2], [3, 4]])

# define a custom scaling function
def my_scaling(X):
    return X /np.max(X)

# create a FunctionTransformer to apply the custom function
custom_transformer = FunctionTransformer(my_scaling)

# apply the transformer to the input data
X_transformed = custom_transformer.transform(X)

# view the transformed data
print(X_transformed)

[[0.25 0.5 ]
 [0.75 1.  ]]


In [18]:
# create a dataset
X = np.array([[1, 2], [3, 4]])

# define a custom scaling function
def my_scaling(X):
    return X / np.max(X)

# create a FunctionTransformer to apply the custom function
custom_transformer = FunctionTransformer(my_scaling)

# apply the transformer to the input data
X_transformed = custom_transformer.transform(X)

# view the transformed data
print(X_transformed)

[[0.25 0.5 ]
 [0.75 1.  ]]
